from . import account_invoice
from . import account_tax
from . import magento_configure
from . import magento_payment_method
from . import magento_product
from . import order_history
from . import product_product
from . import product_sync
from . import product_template
from . import purchase_order
from . import sale_order
from . import sale_order_line
from . import stock_picking
