{
    'name': 'Product Extended Baytonia',
    'version': '11.0',
    'license': 'OPL-1',
    'category': 'Sale',
    'summary': 'Customization on Product for baytonia Co.',
    'author': "Baytonia",
    'website': "https://oddo.baytonia.com/",
    'depends': ['product'],
    'data': ['data/ir_cron.xml',
             ],
    'installable': True,
    'auto_install': False,
    'application': True,
    'active': False,
}
