{
    "name": "Odoo Magento connector Extended",
    "summary": "Module to Find and link Payment method in odoo",
    "version": "1.1.0",
    "sequence": 1,
    "author": "eGrivory || DC",
    "depends": ['odoo_magento_connect', 'eg_send_to_shipper', 'auto_invoice_workflow_ept','stock_mts_mto_rule'],
    "data": [
        "wizard/register_payment_wizard.xml",
        "wizard/whatsapp_message_wizard.xml",
        'views/sale_order_view.xml',
        'views/magento_payment_method.xml',
        'views/magento_configure_view.xml',
        "views/product_product_view.xml",
        'security/ir.model.access.csv',
        'wizard/synchronization_wizard_view.xml',
        'data/mob_server_actions.xml',
        'data/cron.xml',
        "data/cron_for_fetch_product_media.xml",
        "views/account_tax_view.xml",
        "data/cron_for_update_product_quantity.xml",
        "views/purchase_order_view.xml",
        "data/cron_get_orders.xml",
        "views/order_history_view.xml",
        "wizard/import_sale_order_wizard.xml",
        "wizard/stock_update_magento_wizard.xml",

    ],
    "images": [],
    "application": False,
    "installable": True,
    "auto_install": False,
}
